CREATE TABLE IF NOT EXISTS catalog (
    sku TEXT PRIMARY KEY,
    ean TEXT,
    url_images TEXT,
    categorie TEXT,
    modele TEXT,
    size TEXT,
    couleur TEXT,
    asin TEXT,
    url_amazon TEXT,
    collection TEXT,
    key TEXT,
    second_key TEXT,
    parentkey TEXT,
    batch_unit TEXT,
    code_couleur TEXT,
    id_produit TEXT,
    rigide_souple TEXT,
    photos TEXT,
    nouvelles_photos TEXT,
    photos_details TEXT,
    range_pictures TEXT,
    titre_marketplaces TEXT,
    titre_amazon TEXT,
    description_marketplaces TEXT,
    amazon_bulletpoint TEXT,
    bulletpoint1 TEXT,
    bulletpoint2 TEXT,
    bulletpoint3 TEXT,
    bulletpoint4 TEXT,
    bulletpoint5 TEXT,
    bulletpoint6 TEXT,
    bulletpoint7 TEXT,
    composition_exterieure TEXT,
    composition_interieure TEXT,
    trolley TEXT,
    poignee TEXT,
    type_fermeture TEXT,
    nombre_roues INTEGER,
    organisation_interieure TEXT,
    type_cadenas TEXT,
    garantie TEXT,
    dimension_1 TEXT,
    dimension_2 TEXT,
    dimension_3 TEXT,
    dimension_4 TEXT,
    poids_1 TEXT,
    poids_2 TEXT,
    poids_3 TEXT,
    poids_4 TEXT,
    litre_1 TEXT,
    litre_2 TEXT,
    litre_3 TEXT,
    litre_4 TEXT,
    dimension_package TEXT,
    poids_package TEXT,
    extra_data TEXT
);

CREATE TABLE IF NOT EXISTS templates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    partner_name TEXT,
    mapping_json TEXT
);
